apiVersion: v1
kind: Pod
metadata:
  name: config-secret-pod
  namespace: applications
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: database-secret
