apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-demo
  namespace: argocd
  labels:
    managed-by: apps-root

spec:
  project: default

  source:
    repoURL: https://github.com/fab27fc/homelab-devops.git
    targetRevision: main
    path: 01-kubernetes/apps/nginx-demo

  destination:
    server: https://kubernetes.default.svc
    namespace: applications

  syncPolicy:
    automanted:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
