clusterName: "container-platform-eks"
distribution: "eks"

splunkPlatform:
  endpoint: "https://inputs.prd-p-0siro.splunkcloud.com:8088/services/collector/event"
  index: "main"
  logsEnabled: true
  metricsEnabled: false
  tracesEnabled: false
  insecureSkipVerify: true

secret:
  create: false
  name: "splunk-hec-secret"
